# Generated by Django 6.0.5 on 2026-06-02 18:32

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_description_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='product', variations={'thumb': (230, 230)}, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Slug'),
        ),
    ]
